version: '3.8'

services:
  crypto-reels-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - PORT=3003
      - NAFFLES_API_URL=http://host.docker.internal:3000
      - NAFFLES_FRONTEND_URL=http://host.docker.internal:3000
      - NAFFLES_ADMIN_URL=http://host.docker.internal:3001
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - crypto-reels-network
    restart: unless-stopped

  crypto-reels-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - BACKEND_URL=http://crypto-reels-backend:3003
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:3003
      - NAFFLES_API_URL=http://host.docker.internal:3000
      - NAFFLES_FRONTEND_URL=http://host.docker.internal:3000
      - NAFFLES_ADMIN_URL=http://host.docker.internal:3001
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - crypto-reels-network
    depends_on:
      - crypto-reels-backend
    restart: unless-stopped

networks:
  crypto-reels-network:
    driver: bridge